# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/nlms_hw_system/nlms_hw_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nlms_hw_system || ORIG_REF_NAME==nlms_hw_system} -quiet] -quiet

# IP: bd/nlms_hw_system/ip/nlms_hw_system_processing_system7_0_0/nlms_hw_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nlms_hw_system_processing_system7_0_0 || ORIG_REF_NAME==nlms_hw_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/nlms_hw_system/ip/nlms_hw_system_nlms_top_0_0/nlms_hw_system_nlms_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nlms_hw_system_nlms_top_0_0 || ORIG_REF_NAME==nlms_hw_system_nlms_top_0_0} -quiet] -quiet

# IP: bd/nlms_hw_system/ip/nlms_hw_system_axi_bram_ctrl_0_0/nlms_hw_system_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nlms_hw_system_axi_bram_ctrl_0_0 || ORIG_REF_NAME==nlms_hw_system_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/nlms_hw_system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nlms_hw_system_axi_smc_0 || ORIG_REF_NAME==nlms_hw_system_axi_smc_0} -quiet] -quiet

# IP: bd/nlms_hw_system/ip/nlms_hw_system_rst_ps7_0_50M_0/nlms_hw_system_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nlms_hw_system_rst_ps7_0_50M_0 || ORIG_REF_NAME==nlms_hw_system_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/nlms_hw_system_ooc.xdc
