# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.srcs/sources_1/bd/system_top/ip/system_top_axi_bram_ctrl_0_0/system_top_axi_bram_ctrl_0_0.xci
# IP: The module: 'system_top_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.gen/sources_1/bd/system_top/ip/system_top_axi_bram_ctrl_0_0/system_top_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.srcs/sources_1/bd/system_top/ip/system_top_axi_bram_ctrl_0_0/system_top_axi_bram_ctrl_0_0.xci
# IP: The module: 'system_top_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.gen/sources_1/bd/system_top/ip/system_top_axi_bram_ctrl_0_0/system_top_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
