# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.srcs/sources_1/bd/system_top/ip/system_top_nlms_top_0_1/system_top_nlms_top_0_1.xci
# IP: The module: 'system_top_nlms_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.gen/sources_1/bd/system_top/ip/system_top_nlms_top_0_1/src/nlms_constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_nlms_top_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.gen/sources_1/bd/system_top/ip/nlms_acc_ip_new_vivado/nlms_acc_ip_new_vivado.srcs/constrs_1/new/nlms_constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_nlms_top_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.srcs/sources_1/bd/system_top/ip/system_top_nlms_top_0_1/system_top_nlms_top_0_1.xci
# IP: The module: 'system_top_nlms_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.gen/sources_1/bd/system_top/ip/system_top_nlms_top_0_1/src/nlms_constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_nlms_top_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.gen/sources_1/bd/system_top/ip/nlms_acc_ip_new_vivado/nlms_acc_ip_new_vivado.srcs/constrs_1/new/nlms_constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_nlms_top_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
