# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.srcs/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_nlms_top_0_0/nlms_hw_system_nlms_top_0_0.xci
# IP: The module: 'nlms_hw_system_nlms_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_nlms_top_0_0/src/nlms_constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'nlms_hw_system_nlms_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_acc_ip_new_vivado/nlms_acc_ip_new_vivado.srcs/constrs_1/new/nlms_constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'nlms_hw_system_nlms_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.srcs/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_nlms_top_0_0/nlms_hw_system_nlms_top_0_0.xci
# IP: The module: 'nlms_hw_system_nlms_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_nlms_top_0_0/src/nlms_constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'nlms_hw_system_nlms_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_acc_ip_new_vivado/nlms_acc_ip_new_vivado.srcs/constrs_1/new/nlms_constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'nlms_hw_system_nlms_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
