# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.srcs/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/nlms_hw_system_axi_smc_0.xci
# IP: The module: 'nlms_hw_system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/bd_e6eb.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_0/bd_e6eb_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_1/bd_e6eb_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_2/bd_e6eb_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_3/bd_e6eb_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_4/bd_e6eb_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_5/bd_e6eb_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_6/bd_e6eb_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_7/bd_e6eb_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_8/bd_e6eb_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_9/bd_e6eb_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_10/bd_e6eb_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_11/bd_e6eb_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_12/bd_e6eb_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_1/bd_e6eb_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_1/bd_e6eb_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_5/bd_e6eb_s00a2s_0_ooc.xdc

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_6/bd_e6eb_sarn_0_ooc.xdc

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_7/bd_e6eb_srn_0_ooc.xdc

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_8/bd_e6eb_sawn_0_ooc.xdc

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_9/bd_e6eb_swn_0_ooc.xdc

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_10/bd_e6eb_sbn_0_ooc.xdc

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_11/bd_e6eb_m00s2a_0_ooc.xdc

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nlms_hw_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.srcs/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/nlms_hw_system_axi_smc_0.xci
# IP: The module: 'nlms_hw_system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/bd_e6eb.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_0/bd_e6eb_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_1/bd_e6eb_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_2/bd_e6eb_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_3/bd_e6eb_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_4/bd_e6eb_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_5/bd_e6eb_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_6/bd_e6eb_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_7/bd_e6eb_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_8/bd_e6eb_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_9/bd_e6eb_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_10/bd_e6eb_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_11/bd_e6eb_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_12/bd_e6eb_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_1/bd_e6eb_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_1/bd_e6eb_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_5/bd_e6eb_s00a2s_0_ooc.xdc

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_6/bd_e6eb_sarn_0_ooc.xdc

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_7/bd_e6eb_srn_0_ooc.xdc

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_8/bd_e6eb_sawn_0_ooc.xdc

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_9/bd_e6eb_swn_0_ooc.xdc

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_10/bd_e6eb_sbn_0_ooc.xdc

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/bd_0/ip/ip_11/bd_e6eb_m00s2a_0_ooc.xdc

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc_hw/nlms_acc_hw.gen/sources_1/bd/nlms_hw_system/ip/nlms_hw_system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nlms_hw_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
