# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system_top/system_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top || ORIG_REF_NAME==system_top} -quiet] -quiet

# IP: bd/system_top/ip/system_top_axi_bram_ctrl_0_0/system_top_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_axi_bram_ctrl_0_0 || ORIG_REF_NAME==system_top_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/system_top/ip/system_top_microblaze_0_1/system_top_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_microblaze_0_1 || ORIG_REF_NAME==system_top_microblaze_0_1} -quiet] -quiet

# IP: bd/system_top/ip/system_top_dlmb_v10_1/system_top_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_dlmb_v10_1 || ORIG_REF_NAME==system_top_dlmb_v10_1} -quiet] -quiet

# IP: bd/system_top/ip/system_top_ilmb_v10_1/system_top_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_ilmb_v10_1 || ORIG_REF_NAME==system_top_ilmb_v10_1} -quiet] -quiet

# IP: bd/system_top/ip/system_top_dlmb_bram_if_cntlr_1/system_top_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==system_top_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/system_top/ip/system_top_ilmb_bram_if_cntlr_1/system_top_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==system_top_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/system_top/ip/system_top_lmb_bram_1/system_top_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_lmb_bram_1 || ORIG_REF_NAME==system_top_lmb_bram_1} -quiet] -quiet

# IP: bd/system_top/ip/system_top_mdm_1_1/system_top_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_mdm_1_1 || ORIG_REF_NAME==system_top_mdm_1_1} -quiet] -quiet

# IP: bd/system_top/ip/system_top_clk_wiz_1_1/system_top_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_clk_wiz_1_1 || ORIG_REF_NAME==system_top_clk_wiz_1_1} -quiet] -quiet

# IP: bd/system_top/ip/system_top_rst_clk_wiz_1_100M_1/system_top_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==system_top_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/system_top/ip/system_top_axi_smc_1/system_top_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_axi_smc_1 || ORIG_REF_NAME==system_top_axi_smc_1} -quiet] -quiet

# IP: bd/system_top/ip/system_top_bram_ip_top_0_2/system_top_bram_ip_top_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_top_bram_ip_top_0_2 || ORIG_REF_NAME==system_top_bram_ip_top_0_2} -quiet] -quiet

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.gen/sources_1/bd/system_top/system_top_ooc.xdc
