# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.srcs/sources_1/bd/system_top/ip/system_top_clk_wiz_1_2/system_top_clk_wiz_1_2.xci
# IP: The module: 'system_top_clk_wiz_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.gen/sources_1/bd/system_top/ip/system_top_clk_wiz_1_2/system_top_clk_wiz_1_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.gen/sources_1/bd/system_top/ip/system_top_clk_wiz_1_2/system_top_clk_wiz_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.gen/sources_1/bd/system_top/ip/system_top_clk_wiz_1_2/system_top_clk_wiz_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.srcs/sources_1/bd/system_top/ip/system_top_clk_wiz_1_2/system_top_clk_wiz_1_2.xci
# IP: The module: 'system_top_clk_wiz_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.gen/sources_1/bd/system_top/ip/system_top_clk_wiz_1_2/system_top_clk_wiz_1_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.gen/sources_1/bd/system_top/ip/system_top_clk_wiz_1_2/system_top_clk_wiz_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/fpga_projects/SDUP/projekt/nlms_acc/nlms_acc.gen/sources_1/bd/system_top/ip/system_top_clk_wiz_1_2/system_top_clk_wiz_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_top_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
